spring:
  application:
    name: teach-gram
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/teach-gram
    username: postgres
    password: host
  jpa:
    hibernate.ddl-auto: update

security:
  cors: http://localhost:5173/
  secret: bla_bla